# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.box = "bento/ubuntu-20.04"
    # synced folder because I running it from WSL
    config.vm.synced_folder '.', '/vagrant', disabled: true
    config.vm.provision "shell", path: "bootstrap/bootstrap.sh"
  
    # master
    config.vm.define "kmaster" do |kmaster|
      kmaster.vm.box = "bento/ubuntu-20.04"
      kmaster.vm.hostname = "kmaster.example.com"
      kmaster.vm.network "private_network", ip: "172.16.10.100"
      kmaster.vm.provider "virtualbox" do |v|
        v.name = "kmaster"
        v.memory = 2048
        v.cpus = 2
      end
      kmaster.vm.provision "shell", path: "bootstrap/bootstrap_kmaster.sh"
    end
  
    NodeCount = 2
  
    # Kubernetes Worker Nodes
    (1..NodeCount).each do |i|
      config.vm.define "kworker#{i}" do |workernode|
        workernode.vm.box = "bento/ubuntu-20.04"
        workernode.vm.hostname = "kworker#{i}.example.com"
        workernode.vm.network "private_network", ip: "172.16.10.10#{i}"
        workernode.vm.provider "virtualbox" do |v|
          v.name = "kworker#{i}"
          v.memory = 1024
          v.cpus = 1
        end
        workernode.vm.provision "shell", path: "bootstrap/bootstrap_kworker.sh"
      end
    end
  
  end
  