# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.box = "bento/ubuntu-20.04"
    config.vm.synced_folder '.', '/vagrant', disabled: true
    config.vm.hostname = "docker.home.local"
    config.vm.network "private_network", ip: "172.16.10.105"
    config.vm.provider "virtualbox" do |v|
        v.name = "docker"
        v.memory = 2048
        v.cpus = 2
      end

    config.vm.provision "shell", inline: <<-SHELL
      #!/bin/bash
      sudo apt-get update
      sudo apt-get install -y docker.io docker-compose
      sudo usermod -aG docker vagrant
      sudo apt install make
    SHELL
  end